name: Build ARM Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build multi-architecture Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        load: true # Allows you to load the built image into Docker's image store
        tags: your-username/your-image-name:latest
        platforms: linux/arm64,linux/arm/v7
